name: GDPR_Obfuscator

on:
  push:
    branches:
      - main
  

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
      - name: Set Up Env and Requirements
        run: make requirements
      - name: Run Checks
        run: make run-checks
